services:
  pgvector:
    image: pgvector/pgvector:pg17
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USERNAME}
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - 5435:5432
    volumes:
      - boss_pgvector_data:/var/lib/postgresql/data
volumes:
  boss_pgvector_data: